[package]
name = "crud_sailfish"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
sailfish = "0.3.3"
serde = "1.0.130"
